// PRODUCTS
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
export const DETAIL_PRODUCT = 'DETAIL_PRODUCT';
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const FILTER_BY_BRAND = "FILTER_BY_BRAND";
export const FILTER_BY_SIZE = "FILTER_BY_SIZE";

//USER
export const GET_USER_ID = "GET_USER_ID";
export const EDIT_USER = "EDIT_USER";
export const GET_USERS = "GET_USERS";
export const DELETE_USER = "DELETE_USER";
export const GET_ERROR_USER = "GET_ERROR_USER";
export const SEARCH_USER = "SEARCH_USER";
export const GET_ERROR_ADMIN = "GET_ERROR_ADMIN"
export const ADMIN_USER = "ADMIN_USER"

//CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_ERROR_CATEGORY = 'GET_ERROR_CATEGORY';
export const GET_CATEGORY_ID = 'GET_CATEGORY_ID';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SEARCH_CATEGORY = "SEARCH_CATEGORY";

//ORDERS
export const GET_ORDER = 'GET_ORDER';
export const GET_ERROR_ORDER = 'GET_ERROR_ORDER';
export const GET_ORDER_ID = 'GET_ORDER_ID';
export const ADD_ORDER = 'ADD_ORDER';
export const EDIT_ORDER = 'EDIT_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const SEARCH_ORDER = "SEARCH_ORDER";

//AUTHENTICATION
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const GET_USER_BY_ID = "GET_USER_BY_ID";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

//FILTERS
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_NAME = "FILTER_BY_NAME";

//CART
export const ADD_TO_CART = "ADD_TO_CART";
export const DEL_FROM_CART = "DEL_FROM_CART"
export const BUY = "BUY"

//URL
export const URL = "http://localhost:3001/"